basePath: /api/v1
definitions:
  controllers.CreateHallInput:
    properties:
      code:
        type: string
      name:
        type: string
    type: object
  controllers.CreateHallResponse:
    properties:
      hall:
        $ref: '#/definitions/models.Hall'
      message:
        type: string
    type: object
  controllers.CreateTheaterInput:
    properties:
      address:
        type: string
      city:
        type: string
      name:
        type: string
    type: object
  controllers.CreateTheaterResponse:
    properties:
      message:
        type: string
      theater:
        $ref: '#/definitions/models.Theater'
    type: object
  controllers.DeleteTheaterResponse:
    properties:
      message:
        type: string
    type: object
  controllers.LoginInput:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  controllers.LoginResponse:
    properties:
      message:
        type: string
    type: object
  controllers.LogoutResponse:
    properties:
      message:
        type: string
    type: object
  controllers.SignupInput:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  controllers.SignupResponse:
    properties:
      message:
        type: string
      user:
        $ref: '#/definitions/models.User'
    type: object
  controllers.TheaterSearchResponse:
    properties:
      theaters:
        items:
          $ref: '#/definitions/models.Theater'
        type: array
    type: object
  controllers.UpdateHallInput:
    properties:
      name:
        type: string
    type: object
  controllers.UpdateHallResponse:
    properties:
      hall:
        $ref: '#/definitions/models.Hall'
      message:
        type: string
    type: object
  controllers.UpdateTheaterInput:
    properties:
      address:
        type: string
      city:
        type: string
      name:
        type: string
    type: object
  controllers.UpdateTheaterResponse:
    properties:
      message:
        type: string
      theater:
        $ref: '#/definitions/models.Theater'
    type: object
  httputil.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
  httputil.ValidationError:
    properties:
      code:
        example: 400
        type: integer
      errors:
        additionalProperties:
          type: string
        type: object
      message:
        type: string
    type: object
  models.Hall:
    properties:
      code:
        type: string
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
      theater_id:
        type: integer
      updated_at:
        type: string
    type: object
  models.Theater:
    properties:
      address:
        type: string
      city:
        type: string
      created_at:
        type: string
      halls:
        items:
          $ref: '#/definitions/models.Hall'
        type: array
      id:
        type: integer
      manager_id:
        type: integer
      name:
        type: string
      updated_at:
        type: string
    type: object
  models.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: ahmadabdelrazik159@gmail.com
    name: Ahmad Abdelrazik
    url: https://www.github.com/AhmadAbdelrazik
  description: API for managing theaters and shows.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Showtime API
  version: "1.0"
paths:
  /api/login:
    post:
      consumes:
      - application/json
      description: Login existing users to their accounts
      parameters:
      - description: User login data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/controllers.LoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.ValidationError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: User Login
      tags:
      - auth
  /api/logout:
    get:
      description: Logout users from the system.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.LogoutResponse'
      summary: User Logout
      tags:
      - auth
  /api/signup:
    post:
      consumes:
      - application/json
      description: Registers a new user account
      parameters:
      - description: User signup data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/controllers.SignupInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/controllers.SignupResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.ValidationError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: User Signup
      tags:
      - auth
  /api/theaters:
    get:
      description: Search theaters based on name or city
      parameters:
      - description: theater name
        in: query
        name: name
        type: string
      - description: theater city
        in: query
        name: city
        type: string
      - description: sort by city or name
        in: query
        name: sort_by
        type: string
      - description: limit
        in: query
        name: limit
        type: integer
      - description: offset
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.TheaterSearchResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Theaters Search
      tags:
      - theaters
    post:
      consumes:
      - application/json
      description: Creates a new theater
      parameters:
      - description: new theater data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/controllers.CreateTheaterInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/controllers.CreateTheaterResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.ValidationError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Create Theater
      tags:
      - theaters
  /api/theaters/{id}:
    delete:
      description: Delete Theater by ID
      parameters:
      - description: theater id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.DeleteTheaterResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Delete Theater
      tags:
      - theaters
    get:
      description: Get Theater by ID
      parameters:
      - description: theater id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Theater'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Get Theater
      tags:
      - theaters
    patch:
      consumes:
      - application/json
      description: Update an existing theater
      parameters:
      - description: theater id
        in: path
        name: id
        required: true
        type: integer
      - description: updated theater data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/controllers.UpdateTheaterInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/controllers.UpdateTheaterResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.ValidationError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Update Theater
      tags:
      - theaters
  /api/theaters/{id}/halls:
    post:
      consumes:
      - application/json
      description: Creates a new theater's hall
      parameters:
      - description: theater id
        in: path
        name: id
        required: true
        type: integer
      - description: new hall data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/controllers.CreateHallInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/controllers.CreateHallResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.ValidationError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Create Hall
      tags:
      - halls
  /api/theaters/{id}/halls/{code}:
    delete:
      description: Delete theater's hall by Hall Code
      parameters:
      - description: theater id
        in: path
        name: id
        required: true
        type: integer
      - description: hall code
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.DeleteTheaterResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Delete Hall
      tags:
      - halls
    get:
      description: Get Hall by ID
      parameters:
      - description: theater id
        in: path
        name: id
        required: true
        type: integer
      - description: hall code
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Hall'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Get Hall
      tags:
      - halls
    patch:
      consumes:
      - application/json
      description: Updates a new theater's hall
      parameters:
      - description: theater id
        in: path
        name: id
        required: true
        type: integer
      - description: new hall data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/controllers.UpdateHallInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/controllers.UpdateHallResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.ValidationError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Update Hall
      tags:
      - halls
  /api/user-info:
    get:
      description: Logout users from the system.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: User Logout
      tags:
      - auth
swagger: "2.0"
